### ISSUE TITLE
In the search page put the description of the project instead of the text snippet

### ISSUE THREAD

**Issue by D063520** [ec-doris/kohesio.eu#122]
Hi Raph,

can you display the description field and not the text snippet ..... it's included in the API

Salut
Dennis

**Comment by raphdom** [comment]
Hello,

in the search, the rule is:

if we have the snippet than I show it, otherwise I show the description:

` getFullDescription(){
        if (this.snippet){
            return this.snippet;
        }else{
            return this.description;
        }
    }`

**Comment by D063520** [comment]
yes, the goal is to never show the snippet ....

**Comment by raphdom** [comment]
I thought the snippet was to show the part of the description that match with the keyword typed by the user.
Normally we have **bold** in these keywords...
@madewild did you remember that?
Because in the beginning we had the description only, and after we changed.

Regards...

**Comment by D063520** [comment]
Discussed this with Max .... @madewild can you confirm?

**Comment by madewild** [comment]
@raphdom yes sorry we reverted to description only everywhere and no highlighted snippet because of two issues:

- when the match is in the title, we currently show the title twice and no description, which is ugly
- we now allow to search on original title and description, so we would have to show non-English text, or show the English description with no match anyway

**Comment by madewild** [comment]
and also because we cut in mid-sentence with snippets, so for the description we should always put whole sentences if possible

**Comment by raphdom** [comment]
okay, understood, I will change. Thanks for the explanation Max.

**Comment by raphdom** [comment]
done
