### ISSUE TITLE
Duplicate images difficult to distinguish

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#185]
https://kohesio.eu/projects?theme=Low-Carbon-Economy > Audio-visual tab
One image is used 3 times, another 6 times
Hovering over images we can see the URL with QID but maybe we should also show the title in a tooltip (not on mobile though)
Or maybe it's better to deduplicate images in some way, not showing 6 times the same?

**Comment by raphdom** [comment]
The problem here is for this API call I don't have any title or info to display, I have only the image url and the item id
![image](https://user-images.githubusercontent.com/5124917/110637386-a4414b80-81ad-11eb-8dec-dd5f49010493.png)

If you provide me this I can easily do the tooltip or even put like inside the image (bellow) with a transparent background that will cover as well the mobile version.

**Comment by madewild** [comment]
@D063520 can you add this?

**Comment by raphdom** [comment]
good

**Comment by raphdom** [comment]
fixed
