### ISSUE TITLE
Outermost regions ribbon

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio.eu#234]
![OutermostRegions](https://user-images.githubusercontent.com/80402472/125065828-998eb880-e0b2-11eb-91c7-dddcfb270ba3.GIF)

**Comment by madewild** [comment]
Investigate with GISCO team or develop custom solution?
https://ec.europa.eu/eurostat/web/coastal-island-outermost-regions/background

**Comment by raphdom** [comment]
So, finally we have the first version of this feature, on my view maybe we could now zoom in the country, like France we have the world zoom because of the overseas regions. I think if we zoom in only in France, could me more interesting, as now we have a separated panel to this (@D063520):
<img width="1029" alt="Screenshot 2022-01-25 at 18 54 24" src="https://user-images.githubusercontent.com/5124917/151032395-b2cc24d8-4f46-4bac-ad18-bfb1d34ff2f6.png">
 @AThollard don't know if you want to send this version to the team to validate the map interaction.
This is just the first version, can be improved and I need to adapt with the mobile experience...

**Comment by madewild** [comment]
Very nice, thank you @raphdom 
Indeed we should adapt the geometries to zoom in on continental France and Portugal instead of zooming out.

**Comment by AThollard** [comment]
Very nice indeed @raphdom 
One remark on the wording please use 'Outermost regions' rather than 'Overseas regions' -> important to get colleagues from Regio on board.
Also for my understanding, are you going to display this ribbon with all the outermost regions (OR) on the general map, and then when someone clicks on France, reduce the ribbon to French OR only? Or the ribbon appears only when clicking on France, Portugal and Spain?

**Comment by AThollard** [comment]
Happy to show the map to colleagues for validation when these small modifs are done.

**Comment by madewild** [comment]
@AThollard the two options are possible but the one currently implemented (by country) has the advantage of not overwhelming the map with many regions...

**Comment by madewild** [comment]
@raphdom so it's tricky to change the geometries because there is an impact on the filters...
could we try hardcoding the frame (max/min lat/long) for France to zoom by default on the continental part?
for Spain and Portugal not sure it's needed, we can discuss after
also, when zooming on a continental region we should maybe hide the ribbon (show it only at "France" level):
![hide_ribbon](https://user-images.githubusercontent.com/942488/151148720-d5ce52f7-3623-4699-bc9c-dbc65916045b.png)

**Comment by AThollard** [comment]
> @AThollard the two options are possible but the one currently implemented (by country) has the advantage of not overwhelming the map with many regions...
On the other side, it could be a way to give more visibility to the outermost regions that are generally forgotten on maps from the very start. 
Let me discuss this with colleagues internally in Regio (it's a 'communication' decision). The option implemented now is already very good.

**Comment by madewild** [comment]
@svili could you already rename "Overseas regions" into "Outermost regions" in the ribbon?

**Comment by madewild** [comment]
@AThollard it has been renamed now

**Comment by madewild** [comment]
@raphdom we discussed this during the meeting, could you try adding the ribbon with all 8 regions on the main map? it would also address comments by REGIO colleagues that the right part of the map is out of EU scope so can be hidden (instead of resizing the map)

also, could you aligne the width of the ribbon with the "Projects near me" button above?

**Comment by madewild** [comment]
And reminder: hardcode the frame (max/min lat/long) to zoom by default on the continental part for France **but also Spain and Portugal**

**Comment by madewild** [comment]
Oh sorry and also: disable the ribbon (or improve) on mobile:
![ribbon_mobile](https://user-images.githubusercontent.com/942488/151539322-49d9f3d1-fc79-40ce-9b0b-173fb95ed018.png)

**Comment by raphdom** [comment]
Everything was implemented, except the mobile experience that I still need to prettify, for now I just disabled the ribbon on mobile devices. Can you test, please?

**Comment by madewild** [comment]
Very nice! @AThollard @roberto-musmeci  can you have a look?

There is only this comment:

> also, when zooming on a continental region we should maybe hide the ribbon (show it only at "France" level): ![hide_ribbon](https://user-images.githubusercontent.com/942488/151148720-d5ce52f7-3623-4699-bc9c-dbc65916045b.png)

@AThollard what do you think? we leave like it is or hide the ribbon when zooming on a continental region?

**Comment by roberto-musmeci** [comment]
Very good implementation. Thanks @raphdom :) 
For coherence, I would be in favour of hiding the outermost ribbon when zooming in a region.

**Comment by madewild** [comment]
@raphdom can you try implementing this?

**Comment by AThollard** [comment]
@raphdom @madewild maybe  not related but the project near me does not work anymore on dev.kohesio.eu

**Comment by madewild** [comment]
it works for me... maybe you need to refresh the cache?

something else @raphdom : we need to handle the ribbon properly on the projects results...
for instance https://dev.kohesio.eu/projects?keywords=youth&sort=Total-Budget-(descending) > Map tab
![results_map](https://user-images.githubusercontent.com/942488/152132163-1e058c86-0896-4248-b4ce-7c6ce7aa039d.png)

The ORs are shown even if 0 results... not ideal. Or we hide the ribbon on that map?

**Comment by raphdom** [comment]
For me we should hide it and create another issue to implement this. There is a lot of complexity around the filters in the project page.

**Comment by madewild** [comment]
I agree, so @AThollard we propose to hide on that page + on mobile for now and use it only in the front page map

**Comment by AThollard** [comment]
> @raphdom @madewild maybe not related but the project near me does not work anymore on dev.kohesio.eu

It works now! probably a network issue from my side.

**Comment by raphdom** [comment]
Everything was implemented as discussed, can you test please?

**Comment by madewild** [comment]
For me we can close, @AThollard agreed?

**Comment by AThollard** [comment]
Great job! thanks @raphdom 
We can close the issue. For me good to go for version 1.0.
If we need to adapt the label Guadeloupe->Guadeloupe/St Martin we will do it for version 1.2. And I would really prefer to stick to the NUTS labels as it is now (to be discussed internally in REGIO)
