### ISSUE TITLE
Accessing projects in the Map tab - title not displayed

### ISSUE THREAD

**Issue by AThollard** [ec-doris/kohesio.eu#274]
Issue accessing projects - Search: Just transition (keyword)-> Map tab> Zoom in Paris
![image](https://user-images.githubusercontent.com/80402472/135884391-09bad9b4-061f-4c1d-ab6e-e8a03b7e3260.png)

**Comment by AThollard** [comment]
@madewild @raphdom

**Comment by madewild** [comment]
Mmmh, and projects are not aligned between the results and the map!

https://kohesio.eu/projects?keywords=just%20transition&country=France&region=%C3%8Ele-de-France
@D063520 @AlyHdr

**Comment by madewild** [comment]
Both the results and the map show 3 projects, but they have only one in common!

**Comment by D063520** [comment]
I quickly checked ....

there are three coordinates in the map:

<img width="1678" alt="Screenshot 2021-10-04 at 19 36 24" src="https://user-images.githubusercontent.com/10883585/135897839-2631ea17-e213-48de-8320-9f750b72d6d8.png">

and I can find these 3 attached to the projects

<img width="1678" alt="Screenshot 2021-10-04 at 19 36 59" src="https://user-images.githubusercontent.com/10883585/135897929-12656c60-265a-4564-92da-aa4f8dbc9f32.png">

so the API seams aligned, probably the problem is somewhere else .....

**Comment by madewild** [comment]
The problem seems to come from this api: https://kohesio.linkedopendata.eu/api/facet/eu/search/project/map/point?keywords=just%20transition&country=https://linkedopendata.eu/entity/Q20&region=https://linkedopendata.eu/entity/Q2616107&coordinate=2.291709093592,48.83717225

**Comment by madewild** [comment]
And https://kohesio.linkedopendata.eu/api/facet/eu/search/project/map/point?keywords=just%20transition&country=https://linkedopendata.eu/entity/Q20&region=https://linkedopendata.eu/entity/Q2616107&coordinate=2.4393518918543,48.859270124851 return project https://linkedopendata.eu/entity/Q139285 instead of https://linkedopendata.eu/entity/Q139926

**Comment by D063520** [comment]
the keywords where not expanded .....

https://dev.kohesio.eu/projects?keywords=Just%20transition&country=France&region=Île-de-France

deployed this to dev. I can merge to master if you approve

**Comment by madewild** [comment]
yes looking fine on dev, for me you can merge! :) thx
