### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#28]
Allow to sort projects by date, amount, etc.

**Comment by D063520** [comment]
Hello,

the backend is now prepared for this ..... we deployed the new API in dev:

https://kohesio.linkedopendata.eu/swagger-ui.html#/facet-dev-controller/euSearchProjectUsingGET_1

the parameters are orderEndDate, orderStartDate, orderTotalBudget, orderEuBudget. They are boolean. If they are not passed results order will be "random", as it comes from the index. If it is true/false it is ascending/descending.

@raphdom can you try to implement this in the frontend so that we can test?

Some of these requests are heavy, have toi include them into the cache ....

Salut

**Comment by raphdom** [comment]
Hey Dennis,

I will add this on frontend for sure, but this week I am very busy, maybe next week if it is good for you?

Regards,

Raphael

**Comment by madewild** [comment]
Take your time, I told REGIO you were busy and that they should not expect too much change on the frontend before 15 October...

**Comment by raphdom** [comment]
It is done. Dennis, you can proceed with the tests, please?

**Comment by D063520** [comment]
cool! I think it works out no .... some more caching and it should be there. Some things I noticed:

- Eu Budget (**descending**) -> is it no ascending? it's the same for all the fields
- For better UI I would suggest that the user can only order by the fields that are displayed, EuBudget, StartDate and End Date and that we put in the UI arrows on top of that fields

**Comment by raphdom** [comment]
I don't understand the descending part: You said "If they are true/false the order is ascending/descending." If the user select "EU Budget(ascending)" then it is "orderEuBudget: true" otherwise the "Eu Budget(descending) it will be "orderEuBudget: false".

The second suggestion I think, as we don't have columns headers, it is not good to put arrows close to the fields directly, can be misleading. I can always discuss with Teodora to see a better way to display that. For example in the beneficiaries page it will make more sense to put these arrows that you mention... We can see together what is the best.

**Comment by D063520** [comment]
About the ascending/descending part .... if you query for example this:

https://dev.kohesio.eu/projects?keywords=water

and then you order by EU budget ascending then in the list you will see the project budget decreasing,  but it should be the other way around or?

About the second thing ..... yes let's think more about a nice solution .....

**Comment by raphdom** [comment]
for me yes, should be in another way around.

but when I choose the EU Budged(ascending) I am doing this query 

https://kohesio.linkedopendata.eu/api/dev/facet/eu/search/project?offset=0&limit=15&keywords=water&orderEuBudget=true

Let me know if you want to change it.

Anyway, the normal sort in API's is not like that, you have a field in the query with the fieldname that you want to sort, like sort=euBudget and another field with the direction that can be sortOrder=asc and sortOrder=desc. Let me know if you want to implement like that, I think make more sense and it will be more flexible if you want to add/remove sorts. In the future you can even provide me an endpoint to get the possible sort list.

**Comment by D063520** [comment]
ok, I changed the APi for now, if I implement something similar I will stick to the APi convention you describe ... salut

**Comment by raphdom** [comment]
ok, then we can close this?
