### ISSUE TITLE
Project icon 

### ISSUE THREAD

**Issue by roberto-musmeci** [ec-doris/kohesio.eu#301]
I noticed that for some projects the icon is missing in the project fiche. 
However, the icon is present in the list of operations.
I would say that is is very low priority. I just open the issue so we rember to fix at some point. 

A few examples 
https://kohesio.eu/projects/Q2547990
https://kohesio.eu/projects/Q2854126

---
_List of results_ 
![image](https://user-images.githubusercontent.com/86654885/150518479-719552b4-8af4-4065-8dcd-5b428243bd66.png)

----
_Project fiche_

![image](https://user-images.githubusercontent.com/86654885/150518547-49c25c88-24c0-493f-9c64-23498380b294.png)

**Comment by madewild** [comment]
I think there is a bug and it it never shown! ;)

@raphdom there is a class called class="default-theme-image ng-star-inserted" but no image appears... can you investigate?

**Comment by svili** [comment]
I fixed this, but just to signal what was the problem here:
The endpoint `https://dev.kohesio.linkedopendata.eu/api/facet/eu/project` doesnt return an `objectiveId` field but an `objectiveIds` list of strings.
On the project listing view this objectId is being used, so I guess that API returns this field normally.
I fixed by adding the objectiveIds field to the Project model and using that on the project detail view.
But this is probably a bug on the backend side.

**Comment by D063520** [comment]
I do not remember exactly, but my guess is that at the beginning we thought a project has only one thematic objective. But this is not true. It has multiple, so objectiveIds is fine. So I would keep it like this and close this issue ....

**Comment by madewild** [comment]
indeed it's normal, we changed from id to ids

**Comment by madewild** [comment]
Fixed, @roberto-musmeci you can verify on:
https://dev.kohesio.eu/projects/Q2547990
https://dev.kohesio.eu/projects/Q2854126

However, we have a date modeling issue for projects with multiple TOs... For instance https://dev.kohesio.eu/projects/Q68696 has 2 themes but only one of the two icons can be displayed (at random?). So here "Education & Training" is listed in the themes but ignored for the icon, and also in the project results list. @roberto-musmeci you are aware of this?
