### ISSUE TITLE
Email issues

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#368]
Today I noticed that the email address used on project and beneficiary detail page (behind orange icon) was still mail@example.com! ;) I changed to REGIO-EXTERNAL-COMMUNICATION@ec.europa.eu but this made me realise two things:

1. the email used in the footer etc. is REGIO-EXTERNAL-COMMUNICATION@ec.europa.eu but the one on the about page is REGIO-KM@ec.europa.eu, @AThollard is this normal?
2. the email icon in the footer below "Follow us on" is redundant with the "Contact" link. Moreover, "follow us on email" is strange, I would remove it and leave just the Contact (maybe this will change with ECL footer?)

**Comment by AThollard** [comment]
To be aligned with ECL and adapt from InfoRegio footer: https://ec.europa.eu/regional_policy/en/contact/
(adding REGIO-EXTERNAL-Communication@ec.europa.eu or REGIO-KM@ec.europa.eu ? or webmaster? @gachpas @roberto-musmeci  @Bisiaam 
In addition check the links behind social media icons with Social media team.
Not urgent-> v1.1

**Comment by Bisiaam** [comment]
I would say External comm but don't have a strong opinion on that

**Comment by gachpas** [comment]
@madewild , I have prepared a document (under reviw by Anne roght now) that harmonise the contact detail in footer and pages accessible from the footer. You shoudl have this doc tomorrow. Do you see other pages where contact info is displayed?

cc: @AThollard

**Comment by madewild** [comment]
On https://kohesio.development.ec.europa.eu/projects/Q100952 and https://kohesio.development.ec.europa.eu/beneficiaries/Q2514974 there is an email icon that is currently pointing to REGIO-EXTERNAL-COMMUNICATION@ec.europa.eu
We could just remove it and leave social media icons only...

**Comment by gachpas** [comment]
Hello @madewild ,

the good thing is that THE email address for contact is that one (Alex'steam FMB) ;)

The problem is that this enveloppe is part of the Sharing possibilities, and therefore, I would expect that clicking it just opens an email to which the user woud add whatever recipients is needed to share...
@AThollard , do you agree with this?

**Comment by AThollard** [comment]
Good morning @gachpas and @madewild 
I share your views @gachpas on the expected behaviour, it should open an email with possibly a link to the project and the ability to share by email.
However, if we don't have it ready, we can just remove the icon from the package unless @madewild has a ready to go solution.

**Comment by madewild** [comment]
We can discuss this on #480 
I will investigate...

**Comment by madewild** [comment]
@gachpas @AThollard @Bisiaam do you still see email issues on dev? or can we close this?

**Comment by gachpas** [comment]
@madewild , the share via email feature is now working as expected :)
Thx
