### ISSUE TITLE
Map side effects

### ISSUE THREAD

**Issue by raphdom** [ec-doris/kohesio.eu#400]
- [x] Feature Collapse Regions Names
- [x] Responsive design
- [x] Mobile experience
- [x] Title outermost regions
- [x] Doesn’t work on project list page
- [x] Modal detail page integration

**Comment by madewild** [comment]
I changed the bullet points to checkboxes so that we can tick what is done...

**Comment by raphdom** [comment]
Everything was fixed. Can you check @madewild ?

**Comment by madewild** [comment]
Great, just two small things:

- the outermost region stays there empty instead of disappearing completely when non-relevant country (e.g. Germany) selected:
![outer_stays](https://user-images.githubusercontent.com/942488/154140125-2a97333f-8562-4060-9ceb-ddab047ad498.png)

- the css of the list of projects is quite bad:
![map_proj_css](https://user-images.githubusercontent.com/942488/154140164-07f374e0-6720-4f98-bc40-f29a41cd090a.png)

Do you want me to open separate issues for these?

**Comment by raphdom** [comment]
please and put to the other release
