### ISSUE TITLE
Add filters to breadcrumb

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#65]
Currently if we are on a project detail page and click "Projects" in the breadcrumb to come back, all filters are lost. We should maybe add the GET parameters in the URL behind "Projects" in the breadcrump, e.g. https://kohesio.eu/projects?country=Italy&theme=Climate-Change-Adaptation-%26-Risk-Prevention

**Comment by raphdom** [comment]
I've discussed this with Dennis and Teodora and we think that the breadcrumbs don't have this purpose, it will be weird because the breadcrumb is made to navigate between the pages, if the user want to go back to the previous search he should use the back button of the browser... Maybe the breadcrumbs in the detail page is useless and we can remove it, because have only a link for the home page, that we already have in the logo, and the link for the projects, that we have on top right of the page.

**Comment by madewild** [comment]
Agreed, maybe we should remove the breadcrumb altogether in future version?
